### ISSUE TITLE
Blocking issue

### ISSUE THREAD

**Issue by Umity** [kylewetton/image-compare-viewer#10]
Hi again Kyle

your implementation of preventing screen moving upside down when we are swiping the before/after images was a great addition. 

But there is a new problem now. It is also blocking the upside/down swipe which is a natural behaviour for visitors to browse the page. To tackle the problem, user should tap on another location rather than image-compare div. Imagine a web designer would like to put several image-compare images, then it would be very annoying to find a space so that visitors can browse the page upside/down. 

To tackle the problem, do you think you can freeze the screen movements when a user touches to ".icv__control" ?

**Comment by Umity** [comment]
This will also mean disabling the slider to move where touch begin behavior.

**Comment by kylewetton** [comment]
Sorry for the late turn around on this, I've fixed that up. Mobile users will need to interact with the control itself to move the slider, it feels much better now. Let me know if it works as expected and of course if I've missed anything. Cheers!

**Comment by Umity** [comment]
Hey Kyle, that looks and feels like a native app! It is amazing. Thank you so much for this. I have a private problem (not so much related to this library), do you mind to give me your email?

**Comment by kyleatblackfoot** [comment]
Awesome man, happy to help. email is kylewetton at icloud dot com
