### ISSUE TITLE
IE11 Support

### ISSUE THREAD

**Issue by ben4d85** [kylewetton/image-compare-viewer#16]
Is there a way to get this to work in IE11?

**Comment by kylewetton** [comment]
Possibly, I'll look into it for you. I wonder if it needs more bundle crunching. With Edge and Edge Chromium having proceeded IE11, I haven't personally spent much time testing on IE. (I also only have a Mac at home to work on).

**Comment by ben4d85** [comment]
Thank you! At the moment, the images on [your demo page](https://image-compare-viewer.netlify.app/) get displayed vertically stacked, with no slider.

IE 11 console shows:
```
SCRIPT1002: Syntax error
File: 1.21b8e5d2.chunk.js, Line: 1, Column: 12427.
```

Looking at that, it's creating a class with a constructor. See this for reference: https://stackoverflow.com/questions/37194202/ie11-gives-script1002-error-when-defining-class-in-javascript

Hope it helps!

**Comment by stijnelskens** [comment]
@kylewetton Did you allready looked into this? Have the same problem!

**Comment by stijnelskens** [comment]
Any updates??

**Comment by kyleatblackfoot** [comment]
Hey @stijnelskens, I use ES6 class syntax for this slider because I don't personally support IE11, best bet here would be to look into Babel and see if you can edit the bundle settings or fork the repo and make a version that suites your browser needs. Sorry I can't be of more help there!
