### ISSUE TITLE
Styles from CDN Not Applying

### ISSUE THREAD

**Issue by jaredforth** [kylewetton/image-compare-viewer#19]
I have followed the documentation exactly to set up the viewer. 

I am loading CSS and JS from the CDN: 

```html
<link type="text/css" href="https://unpkg.com/image-compare-viewer/dist/image-compare-viewer.min.css">
<script src="https://unpkg.com/image-compare-viewer/dist/image-compare-viewer.min.js"></script>
```

My HTML is structured: 

```html
<div id="image-compare">
    <img src="/uploads/car1.jpeg" alt="" />
    <img src="/static/uploads/car2.jpeg" alt="" />
</div>
```

My JS: 

```html
<script>
    const element = document.getElementById("image-compare");
    const viewer = new ImageCompare(element).mount();
</script>
```

However, the result looks like this: 

![localhost_1313_gallery_](https://user-images.githubusercontent.com/33227005/110220539-dee47480-7e8b-11eb-880f-7e0266e05312.png)

It seems that the CSS is not being loaded from the CDN. Why would this be the case?

**Comment by kylewetton** [comment]
Bizarre! I'll read up about whats happened here, but it looks like type="text/css" isn't working in this case,

Change this
`<link type="text/css" href="https://unpkg.com/image-compare-viewer/dist/image-compare-viewer.min.css">`

To this (notice that we're changing it to rel="stylesheet")

`<link rel="stylesheet" href="https://unpkg.com/image-compare-viewer/dist/image-compare-viewer.min.css">`

I think it might have something to do with unpkgs redirection setup

**Comment by lucacataldo** [comment]
Just a heads-up that this issue is still happening. Maybe it'd be best to change the README to use `rel="stylesheet"` since copying the snippet from there and following the docs yields this exact issue

**Comment by netpyoung** [comment]
and one more thing error on document is `querySelectorAll`

for query ion d is `querySelectorAll("#id")`

for query on class is `querySelectorAll(".class")`

**Comment by alt9800** [comment]
I was suffering from the same issue, applied <rel="stylesheet"> and it worked fine!
Thanks!
