### ISSUE TITLE
Is there any way to add Label on both of the images?

### ISSUE THREAD

**Issue by jogeshpi03** [kylewetton/image-compare-viewer#3]
I like to know if there is a way to add Labels on both of the images and highlight hover.

**Comment by kylewetton** [comment]
Hey mate, I've just added this feature for you

I've added two new options

**For the default labels**

  ````
{
    showLabels: true
}
````
 
**For labels with options**

````
{
  showLabels: true,
   labelOptions: {
    onHover: true,
    before: 'Draft',
    after: 'Final'
  }
````

Furthermore, if you'd like to style these, you can target the elements with

`.icv__label` for both, and `icv__label-before`, `icv__label-after` for the individual labels. Please let me know how this goes for you. If it all works the way you'd hope, I'll update the docs to include it. Thanks for using it!

**Comment by jogeshpi03** [comment]
hello kyle, it is wonderful and thank you for this newer option.
