### ISSUE TITLE
GitHub demo (and implementation) does NOT work

### ISSUE THREAD

**Issue by dylanh724** [kylewetton/image-compare-viewer#35]
On Win10 with Firefox, Edge and Chrome: **Everything is broken.**

1. Even the untouched GitHub demo doesn't work (after not being able to get it to work on my own project that was very vanilla).
2. After trying to implement on my own site with the vanilla basics using js/css CDN, I had the same result (just plain images stacking vertically).
3. I tried Incognito modes - it's not extensions.
4. Screenshot + GIF below.

# Screenshot

![image](https://user-images.githubusercontent.com/8840024/135747789-8cc6017e-0ba3-4561-82ca-a70bad1f0701.png)

## GIF
https://giphy.com/gifs/nvvjtIGAav8GBf5Uvt

**Comment by kylewetton** [comment]
Hey mate, that's not a demo. It's just a file I use when I want to test it out during development. I disable it when packaging the build. If you'd like to play around with it, bring in commented-out lines (the styles at the top of the index.js file, and the implementation code at the bottom of the file).

**Comment by kylewetton** [comment]
These demos are running the latest build via CDN
https://image-compare-viewer.netlify.app/
