### ISSUE TITLE
Slider control beyond the limits

### ISSUE THREAD

**Issue by LouisCuvelier** [kylewetton/image-compare-viewer#4]
Hi @kylewetton 

**Thanks for this package. It works super great !** 💯

Just a quick feedback :

1. As you can see [here](https://www.w3schools.com/howto/howto_js_image_comparison.asp) when you select the control and keep your mouse pressed while leaving the image container, and you come back to the container, you have always the control.
2. But with `image-compare-viewer`, when you leave the container with the mouse pressed and you come back, you loose the control. You have to click again.

I would be nice to have the same behaviour like described first especially when you reach the limits of the container.

**Comment by kylewetton** [comment]
@LouisCuvelier mate I've fixed this for you, good catch! Thanks for the feedback and taking the time to let me know. Give the demos a hard refresh and give it a go

https://image-compare-viewer.netlify.app/

**Comment by LouisCuvelier** [comment]
You rock, thanks !

**Comment by kylewetton** [comment]
If you're using this in a project anywhere I'd love to see it by the way

**Comment by LouisCuvelier** [comment]
Just to continue about the issue, is this an expected behaviour ?

1. Go beyond the left or right container's limit
2. Drop the left click
3. Go back to the container
4. Observe that you can still move the control without the mouse clicked.

You can compare (again) with the [w3schools script](https://www.w3schools.com/howto/howto_js_image_comparison.asp)

---
> If you're using this in a project anywhere I'd love to see it by the way

You can see it in action [here](https://www.bulneo.fr/realisations/). 😀

**Comment by kylewetton** [comment]
Thanks for catching that, I've fixed this one too. Awesome site! Great to see it in action

**Comment by LouisCuvelier** [comment]
Thanks a lot for your work 🙌
