### ISSUE TITLE
Prevent selection

### ISSUE THREAD

**Issue by LouisCuvelier** [kylewetton/image-compare-viewer#5]
Hey @kylewetton, it's me again, 🤭

Do you think it is possible to apply an `user-select: none;` on the whole page (e.g. body) to prevent selection when the sliding is going beyond the limit of the container ?

**Comment by kylewetton** [comment]
Hey, this is done, give it a go and let me know how it works

**Comment by kylewetton** [comment]
PS This change happens in both the JS and CSS so be sure to update both

**Comment by LouisCuvelier** [comment]
I can't build anymore with webpack because of this error 
```
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> .icv {
|   position: relative;
|   overflow: hidden;
```

Do you have any clue ?

**Comment by kylewetton** [comment]
Yep I accidentally forgot to comment out the scss loading into the js file. Try it now?

**Comment by LouisCuvelier** [comment]
This is working perfectly, thank you !
