### ISSUE TITLE
Weird behaviour on Safari with 2 cols

### ISSUE THREAD

**Issue by LouisCuvelier** [kylewetton/image-compare-viewer#7]
I've noticed a very strange behaviour only on Safari.

I'm using a 2 column layout with `column-count: 2;`.
As you can see [here (on a staging site)](https://staging.bulneo.fr/realisations/), the images with `image-compare-viewer` on the second col are completely bugged. But, when I restore to only one col or any other `display: grid|flex;` it works just fine.

You can compare the staging with the prod version, working with a grid layout [here](https://www.bulneo.fr/realisations/).

I did some test but I have not been able to determine if the problem comes from the JS or Safari 🤷‍♂️. Any idea ?

**Comment by kylewetton** [comment]
Wow what on earth is going on here! You're using Webpack right? Do you have autoprefixer in your build step? (Just an idea). I'll run this same setup in a distilled demo and debug this one.

**Comment by kylewetton** [comment]
Okay so the bug lies in your container styles. Looks like Safari doesn't use column-count that well. It looks like this property is more intended for paragraph columns like a newspaper. I recommend using Grid here instead. that does fix it up fine.

Does that make sense?

**Comment by kylewetton** [comment]
Is that Tailwind or Bootstrap? A lot of the utility classes are similar, you'd be looking to replace col-count-2 with something like `grid grid-col-2`

**Comment by LouisCuvelier** [comment]
> Wow what on earth is going on here! You're using Webpack right? Do you have autoprefixer in your build step? (Just an idea). I'll run this same setup in a distilled demo and debug this one.

Yes, webpack, with Tailwind and PostCSS that does autoprefix.

> Okay so the bug lies in your container styles. Looks like Safari doesn't use column-count that well. It looks like this property is more intended for paragraph columns like a newspaper. I recommend using Grid here instead. that does fix it up fine.

Safari and its mysteries ... It the browser that is supposed to have the better support of `column-count` 🤦
I preferred to use `column-count` because it provide a nicer flow and breaking. But I will use `grid` for this one 😋

> Is that Tailwind or Bootstrap? A lot of the utility classes are similar, you'd be looking to replace col-count-2 with something like grid grid-col-2

Tailwind everywhere (I love this thing). And yes, `grid grid-cols-2` work nicely.

Thanks for the help !

**Comment by kylewetton** [comment]
Tailwind is the best! I have to be honest with you, I didn't even know column-count existed, I figured I was great at CSS but obviously there's always something to learn

**Comment by LouisCuvelier** [comment]
You can do a [Masonry layout](https://masonry.desandro.com/) without any javascript thanks to `column-count` 😍
