### ISSUE TITLE
Disable scroll when sliding

### ISSUE THREAD

**Issue by LouisCuvelier** [kylewetton/image-compare-viewer#8]
It would be nice if we could disable scrolling when we are sliding, especially on mobile.
[Body Scroll Lock](https://github.com/willmcpo/body-scroll-lock) seems to be a nice solution.

But, to keep `image-compare-viewer` dependency free, we need to have access to events like `onSlidingStart` and `onSlidingEnd` that return the html element.

What do you think ?

**Comment by kylewetton** [comment]
This is something i have experimented with, looks like Body Scroll Lock has figured out the secret to it. I really don't want to add a dependency to ICV, so I'll dig through Body Scroll Lock and see if iI can figure out what they're doing.

**Comment by LouisCuvelier** [comment]
I forgot the "dependency free" in "to keep image-compare-viewer dependency free" in my first message.

Rather than integrating to the package, you can give access with the two events described above, so users can add or not Body Scroll Lock thanks to those events ?

**Comment by kylewetton** [comment]
This is fixed in 1.4.0
